+---------------------+
|       Start         |
+---------------------+
          |
+---------------------+
| Enter marks of Math |
+---------------------+
          |
+------------------------+
| Enter marks of Science |
+------------------------+
          |
+--------------------------+
| Enter marks of English   |
+--------------------------+
          |
        +---------------------------------------------+
        | Are all marks between 0 and 100? (Decision) |
        +---------------------------------------------+
         /                                   \
      No/                                     \Yes
   +-------------------------------+    +---------------------------------------------+
   | Print "Invalid marks entered" |    | Calculate totalMarks = math + science + eng |
   +-------------------------------+    +---------------------------------------------+
   |             |                      |                                             |
   |           End                      | Calculate percentage = totalMarks / 3       |
   |                                    +---------------------------------------------+
   |                                    |                                             |
   |                                    v                                             |
   |                        +-------------------------------+                         |
   |                        | Percentage >= 90 and <= 100?  |                         |
   |                        +-------------------------------+                         |
   |                         /           \                                         ... |
   |                      Yes/             \No                                        |
   |                  +-------------------+   ... (other grade checks)                |
   |                  | Print "Grade: A"  |                                           |
   |                  +-------------------+                                           |
   |                          |                                                        |            
   |                        End                                                       